### ISSUE TITLE
Response Header filter

### ISSUE THREAD

**Issue by jycr** [eclipse-vertx/vertx-http-proxy#11]
Currently, our backends are unable to generate some response headers such as [OWASP Secure Headers](https://wiki.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers)

We need to add these headers before the response reaches the browser.
We thought using this vertx-http-proxy would be a great idea

So it would be great if vertx-http-proxy could provide an API to add this kind of handler.

**Comment by vietj** [comment]
Good idea .

**Comment by vietj** [comment]
we could have a callback on `HttpProxy` that is called before the `ProxyResponse` is sent that will allow to mutate the `ProxyResponse` attributes

**Comment by vietj** [comment]
the new interceptor API should allow this use case

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-http-proxy/pull/32
