### ISSUE TITLE
Support for RoutingContext

### ISSUE THREAD

**Issue by adoignies** [eclipse-vertx/vertx-http-proxy#13]
#### Describe the feature

I'm really interested in this reverse proxy feature, when using it I found that it was not compatible with vertx-web router.

I modified the code just to extends Handler<RoutingContext> instead of Handler<HttpServerRequest>, and the handle method.

It works fine, but i am not sure to see the big picture and i would like your notice on side effects which i did not foreseen.

#### Use cases

A simple usecase is to add several handlers before reverse proxiing and even a redis session handler :

HttpClient proxyClient = vertx.createHttpClient();
HttpProxy proxy = HttpProxy.reverseProxy(proxyClient);
proxy.origin(7070, "localhost");

HttpServer proxyServer = vertx.createHttpServer();
        Router router = Router.router(vertx);

        //add redis session support
        Redis redisClient = Redis.createClient(vertx, new RedisOptions()
                        .setConnectionString("redis://127.0.0.1:6379")
                        .setMaxPoolSize(2)
                        .setMaxPoolWaiting(32));
        SessionStore store = RedisSessionStore.create(vertx, redisClient);

        SessionHandler sessionHandler = SessionHandler.create(store);

        router.route().handler(sessionHandler);
        router.route().handler(context -> {
            Session session = context.session();
            session.put("foo", "bar");
            context.next();
        });
        router.route().handler(proxy);
        proxyServer.requestHandler(router).listen(8080);

#### Contribution

I'm willing to contribute and implementing this feature.

Thanks in advance,
Regards,
adoignies

**Comment by vietj** [comment]
we do have an integration pending with Vert.x web here https://github.com/vert-x3/vertx-web/pull/1848

I need to discuss with Paulo what would be the best option to do.

**Comment by adoignies** [comment]
I was indeed missing this module dependency concern.
It is a good news that an integration is scheduled for future 4.1.0 vertx-web
Please keep me inform regarding your best option choice.

Thanks for the quick answer.

**Comment by pmlopes** [comment]
@adoignies how would this integration be different from the one mentioned above?

https://github.com/vert-x3/vertx-web/pull/1848

**Comment by adoignies** [comment]
It is no different. I was unaware of the pending integration. 
A handler<RoutingContext> which wrapped the reverseProxy (as done in vert-x3/vertx-web#1848) seems better.

**Comment by adoignies** [comment]
The dedicated RouterHandler works fine. I close the ticket.
