### ISSUE TITLE
Will it support to rewrite url?

### ISSUE THREAD

**Issue by Linindoo** [eclipse-vertx/vertx-http-proxy#16]
It's  usefull to change the proxy path

**Comment by vietj** [comment]
can you give a pointer to the precise feature you would like to see ?

**Comment by Linindoo** [comment]
> can you give a pointer to the precise feature you would like to see ?

if there is  a raw url like '/a/b/c',I want proxy it to target path '/b/c/', it can not implement at current version

**Comment by vietj** [comment]
where should be this raw URL ?

**Comment by Dieken** [comment]
+1 for this feature.

proxy-server(route on /proxy/*)   ----> origin-server(route on /*)

I would like http://proxy-server/proxy/x/y/z to be proxied to http://origin-server/x/y/z.

**Comment by adoignies** [comment]
Indeed the request path can't be changed in the routingContext.request() object before the ProxyHandler, so maybe some kind of lambda like the originSelector lambda or ProxyOptions should be used to overwrite ProxyRequest attributes like the uri.

**Comment by grigoriadis** [comment]
You can change the original path by setting the URI on the ProxyRequest.

```java
HttpClient proxyClient = vertx.createHttpClient();
Router proxyRouter = Router.router(vertx);
proxyRouter
  .route("/a/b/c")
  .handler(context -> {
    ProxyRequest proxyRequest = ProxyRequest.reverseProxy(context.request());
    proxyRequest.setURI(proxyRequest.getURI().replace("/a", "/"));
  
    proxyClient.request(proxyRequest.getMethod(), elastic.port(), elastic.host(), proxyRequest.getURI())
      .compose(proxyRequest::send)
      .onSuccess(ProxyResponse::send)
      .onFailure(err -> {
        proxyRequest.release();
        context.response().setStatusCode(500).send();
      });
  });
```

**Comment by adoignies** [comment]
So for an integration within the HttpProxy/HttpProxyImpl classes, the PR from https://github.com/eclipse-vertx/vertx-http-proxy/pull/19/commits should be a good way to enchance the reverse proxy. It lacks only a test. I'll give it a try when i have the time.

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-http-proxy/pull/32
