### ISSUE TITLE
Transfer-encoding chunked set for all request types

### ISSUE THREAD

**Issue by ibauersachs** [eclipse-vertx/vertx-http-proxy#17]
### Version

4.1.1-SNAPSHOT (46d08aecdf99a2bfd62be65c4c81008cfb7eeb0b)

### Context

The proxy implementation sets `transfer-encoding: chunked` on all HTTP methods. However, GET or HEAD (and probably some others) will almost never have a body. While it's AFAIK not strictly illegal to have a body in GET, it doesn't make sense, it causes issues with our backend (based on Hiawatha), and RFC 7231 sections 4.3 marks it as undefined behavior for GET, HEAD, DELETE and CONNECT.

### Do you have a reproducer?

Not really a reproducer, but this small patches fixes it for me:

```diff
Index: src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java
<+>UTF-8
===================================================================
diff --git a/src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java b/src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java
--- a/src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java	(revision 46d08aecdf99a2bfd62be65c4c81008cfb7eeb0b)
+++ b/src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java
@@ -153,7 +153,10 @@
     if (len >= 0) {
       inboundRequest.putHeader(HttpHeaders.CONTENT_LENGTH, Long.toString(len));
     } else {
-      inboundRequest.setChunked(true);
+      Boolean isChunked = HttpUtils.isChunked(outboundRequest.headers());
+      if (len == -1 && isChunked != null && isChunked) {
+        inboundRequest.setChunked(true);
+      }
     }
 
     Pipe<Buffer> pipe = body.stream().pipe();
```

**Comment by vietj** [comment]
can you provide a PR and add tests ?

**Comment by ibauersachs** [comment]
I'll see what I can do. Do you remember why the existing chunked tests are disabled?

https://github.com/eclipse-vertx/vertx-http-proxy/blob/46d08aecdf99a2bfd62be65c4c81008cfb7eeb0b/src/test/java/io/vertx/httpproxy/ProxyRequestTest.java#L71-L97

**Comment by vietj** [comment]
no I do not, this code was written so long ago, digging the commit
history might help
