### ISSUE TITLE
Header host is skipped in proxyRequest

### ISSUE THREAD

**Issue by adoignies** [eclipse-vertx/vertx-http-proxy#24]
Version: 4.1.4

Hello,

At this line, the host header is not propagated by the proxyrequest.
https://github.com/eclipse-vertx/vertx-http-proxy/blob/main/src/main/java/io/vertx/httpproxy/impl/ProxyRequestImpl.java#L145

It can be troublesome when using the http-proxy as a transparent reverse proxy, and unable to process the request based on virtualhost rules on the services behind the proxies.

Can you please fix the behavior or give the possibility to set the ProxyRequest host header ?

Thanks in advance

**Comment by vietj** [comment]
I'm wondering why the host header is not propagated actually because there is nothing wrong with that (unless we are dealing with an absolute request URI)

**Comment by adoignies** [comment]
Sorry i will try to give more details.
The use case is an access with a public host aaaa.test.com and then proxify to a backend server with a local ip 10.11.12.13.
The header host is setted in this case with the ip of the backend server and not setted with the initial host of the request.
