### ISSUE TITLE
Hang when call blocking operation in handler

### ISSUE THREAD

**Issue by hogmuzzle** [eclipse-vertx/vertx-http-proxy#25]
This is my code
`HttpClient proxyClient = vertx.createHttpClient(new HttpClientOptions(clientOptions));
 HttpServer proxyServer = vertx.createHttpServer(new HttpServerOptions(serverOptions));
 HttpProxy proxy = HttpProxy.reverseProxy(proxyOptions, proxyClient);
 proxy.originSelector(selector);
 proxyServer.requestHandler(new HttpProxy() {
            @Override
            public HttpProxy originSelector(Function<HttpServerRequest, Future<SocketAddress>> selector) {
                return this;
            }

            @Override
            public void handle(HttpServerRequest outboundRequest) {
                handleBefore(outboundRequest)
                        .subscribe()
                        .with(proxy::handle,
                                th -> {
                                    int status = 500;
                                    if (th instanceof NotAuthorizedException) {
                                        status = 401;
                                    }
                                    ProxyUtils.end(ProxyRequest.reverseProxy(outboundRequest), status, th.getMessage());
                                });
            }
        });
 proxyServer.listen(ar -> startFuture.handle(ar.mapEmpty()));

//blocking call here
private Uni<HttpServerRequest> **handleBefore**(HttpServerRequest request) {
        String authHeader = request.headers().get("Authorization");
        if (authHeader == null || !authHeader.startsWith(AUTH_PREFIX)) {
            return Uni.createFrom().failure(new NotAuthorizedException("You are not authorized to perform this operation"));
        }
        String jwt = authHeader.replace(AUTH_PREFIX, "").trim();
        return client.getAbs(keycloakUrl).bearerTokenAuthentication(jwt)
                .send().onFailure().retry().atMost(1)
                .flatMap(resp -> {
                    if (resp.statusCode() == 401) {
                        return Uni.createFrom().failure(new NotAuthorizedException("You are not authorized to perform this operation"));
                    }
                    return Uni.createFrom().item(request);
                });
    }
`

If client.getAbs(keycloakUrl) is called successfully the response never comes back from proxy. Actually any blocking call has the same outcome. 

This code works fine
`HttpServer proxyServer = vertx.getDelegate().createHttpServer(new HttpServerOptions(serverOptions));
Router proxyRouter = Router.router(vertx.getDelegate());
proxyServer.requestHandler(proxyRouter);
proxyServer.listen(proxyPort);

HttpClient proxyClient = vertx.getDelegate().createHttpClient();

proxyRouter.route()
                .method(HttpMethod.POST)
                .method(HttpMethod.GET)
                .method(HttpMethod.DELETE)
                .handler(context -> {
                    ProxyRequest proxyRequest = ProxyRequest.reverseProxy(context.request());
//blocking call here
                    proxyFactory.**handleBefore**(context)
                            .subscribe()
                            .with(ok ->
                                            proxyClient.request(proxyRequest.getMethod(), 9002, "localhost", proxyRequest.getURI())
                                                    .compose(proxyRequest::send)
                                                    .onSuccess(ProxyResponse::send)
                                                    .onFailure(err -> {
                                                        proxyRequest.release();
                                                        context.response().setStatusCode(500).send();
                                                    })
                                    ,
                                    th -> {
                                        proxyRequest.release();
                                        context.response().setStatusCode(500).send();
                                    });

                });`

**Comment by hogmuzzle** [comment]
Sorry it was my fault. 
The request has to paused and resumed properly.

**Comment by EmadAlblueshi** [comment]
Hi, @vietj @hogmuzzle I think this issue should be closed

**Comment by vietj** [comment]
right thank you
