### ISSUE TITLE
Completion handler for user agent responses

### ISSUE THREAD

**Issue by dleen** [eclipse-vertx/vertx-http-proxy#29]
Hi All,

Thanks for creating and maintaining a very useful project! I would like to suggest the following feature which we think would be a useful addition (see use cases below).

- [x] do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
- [x] you shall create a feature request only when it is general purpose enough.
- [x] make sure that the feature is not already implemented

#### Describe the feature

A completion handler such as:
```
  @Fluent
  HttpProxy onProxyResponseCompletion(Handler<AsyncResult<Void>> handler);
```

(or with an equivalent origin request completion handler):
```
  @Fluent
  HttpProxy onProxyRequestCompletion(Handler<AsyncResult<Void>> handler);

  @Fluent
  HttpProxy onProxyResponseCompletion(Handler<AsyncResult<Void>> handler);
```
which are called when the request to the origin is completed: `onProxyRequestCompletion` and when the response to the user agent is completed: `onProxyResponseCompletion`.

#### Use cases

* Track pending/outstanding proxy requests to allow graceful shutdown of the proxy:
  * Each time `handle(HttpServerRequest outboundRequest)` is called increment a counter in the application code
  * Each time the completion handler is called, decrement the counter in `onProxyResponseCompletion`.
  * Before shutting down the proxy, block new incoming requests, wait until the counter reaches zero, finally shut down the proxy.

* Gather latency metrics on overall request proxy time
  * Before calling `handle` start a timer
  * Stop the timer In the completion handler: `onProxyResponseCompletion`
  * Report the proxy latency as the difference between the timers

#### Contribution

I am volunteering for implementing this feature.

**Comment by dleen** [comment]
Hi @vietj , thanks for taking a look! I did a quick attempt at implementing this and I came across one problem that you could quickly help with:

```
[ERROR] diagnostic: /Users/dleen/projects/vertx-http-proxy/src/main/java/io/vertx/httpproxy/HttpProxy.java:87: error: Could not generate model for io.vertx.httpproxy.HttpProxy#onProxyRequestCompletion(io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>>): Cannot use Handler<AsyncResult<Void>>, instead use a Future<Void> return
  HttpProxy onProxyRequestCompletion(Handler<AsyncResult<Void>> handler);
```

because of
```
  @Fluent
  HttpProxy onProxyRequestCompletion(Handler<AsyncResult<Void>> handler);
```

From other parts of the codebase that use `Handler<AsyncResult<Void>>` I see that I can use `@GenIgnore` but I'm not sure what the implications of this are?

**Comment by vietj** [comment]
that's because you need to use a Future instead with something like:

`Future<Void> proxyRequestCompletion()`

**Comment by vietj** [comment]
this project does not use `Handler<AsyncResult<T>>` pattern and only futures as it's a new project
