### ISSUE TITLE
Examples of building on HttpProxy

### ISSUE THREAD

**Issue by geoand** [eclipse-vertx/vertx-http-proxy#33]
The docs mention: `Vert.x Http Proxy is a reverse proxy based on Vert.x, it aims to implement reusable reverse proxy logic to focus on higher concerns.`

However in the examples, there is no mention or even a hint of how to use the Proxy to address the higher concerns.

It would be beneficial to folks new to the project to see examples of what address such higher concerns would look like.

**Comment by vietj** [comment]
note that this will be in Vert.x 4.2.5

**Comment by vietj** [comment]
also keep in mind the project is in tech preview and the API can change (like it does in 4.2.5) to improve the API and get the project enough maturity to leave tech preview, e.g the interceptor API did not exist before 4.2.5 and some stuff has been removed with the new API.

**Comment by vietj** [comment]
and your feedback / contributions might help us a lot too!

**Comment by geoand** [comment]
Understood, I'll play around and provide feedback. Thanks!
