### ISSUE TITLE
Option to auto-override request's HOST HTTP header

### ISSUE THREAD

**Issue by clementgeorge-revolve** [eclipse-vertx/vertx-http-proxy#36]
Hello,

I've experienced troubles while implementing a reverse Proxy based on this library because the incoming request's HOST header was propagated to the proxied server as is. The issue is that some servers use this header to resolve routing the request to the correct virtual hosts. 

I've fix my problem by overidding the incoming request's HOST HEADER, setting the same value as the one I used to configure the `HttpProxy` instance.

I wonder if it couldn't be a configuration option for the library.

**Comment by vietj** [comment]
can you show the code you used ?

**Comment by clementgeorge-revolve** [comment]
Basically, I've something like this (kotlin):

```kotlin
class ServiceProxy(vertx: Vertx) {

    var proxy: HttpProxy = null

    init {
        proxy =
            HttpProxy.reverseProxy(
                vertx.createHttpClient(
                    HttpClientOptions()
                )
            )
        proxy?.origin(443, "123.a.run.app")
    }

    fun handle(request: HttpServerRequest) {
        request
             .headers()
             .set("Host", "123.a.run.app") // 123.a.run.app wasn't responding without this override
        proxy.handle(request)
    }
}
```

**Comment by vietj** [comment]
I think we can add an option for black listing some headers for propagation

**Comment by vietj** [comment]
well not "black list" as it raises some issues with wording of course

**Comment by vietj** [comment]
I think it raise an interesting question with interceptors, should this be removed before or after the interceptors ?

**Comment by vietj** [comment]
I think it makes more sense that the HTTP proxy provides a similar mechanism to remove the host header rather than configuration, this way it is possible to order this with other interceptors

**Comment by clementgeorge-revolve** [comment]
You mean that it would be the default behavior of the HTTP proxy ? I totally agree with this solution.

**Comment by vietj** [comment]
no it would not be the default behavior but the interceptor would exist and could be added easily to the HTTP proxy server
