### ISSUE TITLE
We need to give users more control over origin request. 

### ISSUE THREAD

**Issue by dinstone** [eclipse-vertx/vertx-http-proxy#37]
#### Read me

Read this first before creating an issue:

- do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.
- you shall create a feature request only when it is general purpose enough.
- make sure that the feature is not already

#### Describe the feature

We need to give users more control over origin request. This can be done by returning the request options from the origin selector.
`HttpProxy originSelector(Function<HttpServerRequest, Future<RequestOptions>> selector);`

#### Use cases

With the origin request options, you can proxy the site of the secure port, and control the request timeout, Uri rewriting, and other features. But the current API can not do it.

This is an example of a reverse proxy security site. Unfortunately, it cannot work properly because its connections are built on the TCP layer, not the TLS layer.

`HttpProxy httpProxy = HttpProxy.reverseProxy(client)
            .originSelector(req -> Future.succeededFuture(SocketAddress.inetSocketAddress(443, "vertx.io")));
`

If more origin request options can be exposed, it can work normally。for example：

`
HttpProxy proxy = HttpProxy.reverseProxy(proxyClient).originSelector(req -> {
          RequestOptions requestOptions = new RequestOptions();
          requestOptions.setServer(SocketAddress.inetSocketAddress(443, "origin"));
          requestOptions.setSsl(Boolean.TRUE).setTimeout(1000).putHeader("Host", "origin");
          return Future.succeededFuture(requestOptions);
      });
`

#### Contribution

I think I have the ability to implement this feature, maybe I can try it.

**Comment by dinstone** [comment]
@vietj Please approve whether this PR is feasible. Thanks.

**Comment by vietj** [comment]
I will have a look thanks
