### ISSUE TITLE
request hangs when HttpProxy.handle(request) is called in ContextHandler chain

### ISSUE THREAD

**Issue by tomschulze** [eclipse-vertx/vertx-http-proxy#42]
Vert.x 4.3.7

When I use the http proxy like this, the request hangs until it times out. Am I missing something? Originally, I want to refresh tokens, before calling the proxy.

```java
    router
      .route("/words/*")
      // mock an async call
      .handler((rc) -> rc.vertx().setTimer(1, tid -> rc.next()))
      .handler((rc) -> reverseProxy.handle(rc.request()));
```

### Do you have a reproducer?
* https://github.com/tomschulze/vertx-proxy-reproducer
* spin up the vertx server w/ `./mvnw compile exec:java`
* then access http://127.00.1:8080/words?sl=jirrafe
* the proxy forwards requests to http://api.datamuse.com/words; this is just for demo purposes; can be replaced with any other server

**Comment by vietj** [comment]
hi, sorry for the long answer, you are missing the fact that you need to pause the HttpServerRequest and then resume it, so the code you should look like:

```java
        rc.request().pause();
        rc.vertx().setTimer(1, tid -> {
          rc.request().resume();
          rc.next();
        });
```

**Comment by tomschulze** [comment]
oh okay. thanks so much for the clarification! that solves my problem. is it related to this [comment](https://github.com/eclipse-vertx/vert.x/pull/4317#issuecomment-1077327536)?

**Comment by vietj** [comment]
somehow it is.
