### ISSUE TITLE
SEVERE: Received HTTP message with no request in progress

### ISSUE THREAD

**Issue by TeamAggroDEV** [eclipse-vertx/vertx-http-proxy#45]
### Version

4.3.7 and earlier

### Context

Im getting the error  
io.vertx.core.net.impl.ConnectionBase
SEVERE: Received HTTP message with no request in progress
when trying to reverse-proxy to some of my backends, and onFailure does not catch it

### Do you have a reproducer?

https://gist.github.com/TeamAggroDEV/9f10e8f1f35c2830b9c23a80a4a9ddca

### Steps to reproduce

1. Set up reverse proxy
2. Put the website behind cloudflare
3. Use a slow backend
4. Get 520 Origin Error Status code and see error in Console

### Extra

Ubuntu 20.04, Java 8

**Comment by vietj** [comment]
can you provide a complete reproducer that would help

**Comment by vietj** [comment]
@TeamAggroDEV ping, can you provide a reproducer ?

**Comment by jmaicher** [comment]
We observe a similar issue and correlated it with the session termination indicator CD [1] in haproxy logs. This leads to the mentioned error "Received HTTP message with no request in progress". We were originally investigating a memory leak and enabled `-Dio.netty.leakDetection.level=paranoid`. The LEAK detection logs (see below) also correlated with the aforementioned error. We found it curious that the [responsible code path](https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java#L783) does not invoke `ReferenceCountUtil.release(msg);`, which we saw right before calls for `fail(Throwable error)` in the same class.

```
io.vertx.core.VertxException: Received HTTP message with no request in progress
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:768) ~[ui-gateway.jar:?]
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:752) ~[ui-gateway.jar:?]
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157) ~[ui-gateway.jar:?]

...

LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	Hint: 'handler' will handle the message from this point.
	io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:86)
	io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:25)
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:417)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
```

[1] C = "the TCP session was unexpectedly aborted by the client" and D = "the session was in the DATA phase.", see http://docs.haproxy.org/2.7/configuration.html#8.5

**Comment by TeamAggroDEV** [comment]
Is the reproducer still needed?

**Comment by vietj** [comment]
yes that would help investigate the issue and fix it.

**Comment by TeamAggroDEV** [comment]
https://github.com/TeamAggroDEV/VertxReproducer

After refreshing a few times i also get errors like
io.vertx.core.net.impl.ConnectionBase
SEVERE: NULL

**Comment by vietj** [comment]
how can I use the reproducer ? I set it up and using my browser and I always get a 404 response (which is example.com web serer)

**Comment by TeamAggroDEV** [comment]
Spam-press F5 in your browser, you will start seeing errors. Alternatively, you can send a small flood using LOIC or similar.

**Comment by vietj** [comment]
thanks I think I was able to understand what is happening
