### ISSUE TITLE
ProxyInterceptor could be annotated by @VertxGen(concrete = false)

### ISSUE THREAD

**Issue by lucaspouzac** [eclipse-vertx/vertx-http-proxy#46]
Related to the following issue? : https://github.com/smallrye/smallrye-mutiny-vertx-bindings/issues/713

https://github.com/eclipse-vertx/vertx-http-proxy/blob/102a33a54ed5b6a1d839f08a64d2305834b581fb/src/main/java/io/vertx/httpproxy/ProxyInterceptor.java#L9

**Comment by vietj** [comment]
sure thing, file a PR
