### ISSUE TITLE
RoutingContext not propagated into ProxyContext

### ISSUE THREAD

**Issue by fbuetler** [eclipse-vertx/vertx-http-proxy#50]
### Version

4.4.4

### Context

With the [handle method in the ReverseProxy](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.4.4/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L74) accepting only the `HttpServerRequest`, we loose the `RoutingContext` of the request. In our case we would like to retrieve some information of the routing context in an [interceptor](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.4.4/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L67). With the current implementation this is not possible. There is even an [attachments](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.4.4/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L167) member of the `Proxy` class to save some context in a map, but this is not accesible from outside the interceptor.

Our current approach is to fork the `vertx-http-proxy` and add another methods to `ReverseProxy` that accepts a `RoutingContext` and propagate it into the `ProxyContext` with:

```java
        final Proxy proxy = new Proxy(proxyRequest);
        proxy.set(CONTEXT_AWARE_REVERSE_PROXY_KEY, ctx);
        proxy.filters = interceptors.listIterator();
        proxy.sendRequest().compose(proxy::sendProxyResponse);
```
([original snippet](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.4.4/src/main/java/io/vertx/httpproxy/impl/ReverseProxy.java#L93-L95))

With this we can then access the `RoutingContext` from an interceptor.

I am aware that the added method is not part of the [HttpProxy interface](https://github.com/eclipse-vertx/vertx-http-proxy/blob/4.4.4/src/main/java/io/vertx/httpproxy/HttpProxy.java#L34) that the `ReverseProxy` implements.

We would like to help to find a solution that can be integrated into this project (our fork should only be a temporary fix).
How should we tackle this issue?

**Comment by vietj** [comment]
maybe the simplest way would be to have the current `HttpServerRequestWrapper` used by vertx web allow to get the context from it.

io.vertx.ext.web.impl.HttpServerRequestWrapper would implement an interface (e.g io.vertx.ext.WebServerRequest) that has an accessor of the routing context.

inside the interceptor then you can assume to cast HttpServerRequest to WebServerRequest and get the context.

**Comment by fbuetler** [comment]
To be sure, I understand your proposal correctly, I tried to put that into code:

You propose to have a new `WebServerRequest` interface allowing to access the routing context:

```java
package io.vertx.ext.web;

import io.vertx.core.http.HttpServerRequest;

public interface WebServerRequest extends HttpServerRequest {

  public abstract RoutingContext routingContext();

}
```

And to make `HttpServerRequestWrapper` in `vertx-web` to implement that interface:

```java
class HttpServerRequestWrapper extends io.vertx.core.http.impl.HttpServerRequestWrapper implements WebServerRequest {

  // other variables
  private RoutingContext ctx;

  // other constructors

  HttpServerRequestWrapper(HttpServerRequest request, AllowForwardHeaders allowForward, RoutingContext ctx) {
    super((HttpServerRequestInternal) request);
    forwardedParser = new ForwardedParser(request, allowForward);
    this.ctx = ctx;
  }

  // other methods

  @Override
  public RoutingContext routingContext() {
    return ctx;
  }
}
```

I added a new constructor accepting the routing context, to be backwards compatible, instead of replacing it.

Did I understand your proposal correctly?

**Comment by fbuetler** [comment]
@tsegismont 

Yes, this is correct, the new constructor is not invoked by `vertx-web` and you would need to wrap an `HttpServerRequest` yourself and pass it to the proxy, like 

```java
HttpProxy.reverseProxy(...).handle(new HttpServerRequestWrapper(ctx.request(), ctx));
```

In an interceptor, the request can then be casted to an `HttpServerRequestWrapper` (with appropriate checks), like

```java
(HttpServerRequestWrapper) proxyContext.request().proxiedRequest()
```

and access the routing context.

Not pretty, but an easy solution.

**Comment by tsegismont** [comment]
Thanks for the details @fbuetler 

I think we should update the code so that Vert.x Web always sets the routing context in the `HttpServerRequestWrapper` instead of expecting that a `Route` handler implementation does it.

In the current implementation, `HttpServerRequestWrapper` implements `WebServerRequest` but invocations of `routingContext()` always returns `null`. That's confusing. I'll send PRs.
