### ISSUE TITLE
in ProxyInterceptor,fail or throw exception is not handler in failureHandler

### ISSUE THREAD

**Issue by afei00615** [eclipse-vertx/vertx-http-proxy#52]
### Questions

in the ProxyInterceptor, when i throw a RunTimeException or promise.fail() , the router's failureHandler can't catch the excetion, in the vert.x web handler ,it is work ok

### Version

4.4

**Comment by tsegismont** [comment]
Can you please share a small reproducer?

**Comment by afei00615** [comment]
ok,
In global router , I set the failureHandler :
`router.route().failureHandler(new CommonFailureHandler());`
the CommonFailureHandler like this:
`public class CommonFailureHandler implements Handler<RoutingContext> {

    @Override
    public void handle(RoutingContext ctx) {
        log.info("handler failure");
        Throwable throwable = ctx.failure();
        ResultCode resultCode;
        if (throwable instanceof PlatformException) {
            PlatformException platformException = (PlatformException) throwable;
            resultCode = platformException.getResultCode();
        } else if (throwable instanceof HttpException) {
            resultCode = ResultCode.fromHttpStatus(((HttpException)throwable).getStatusCode());
        } else {
            resultCode = ResultCode.EXECUTION_ERROR;
        }
        ctx.response().setStatusCode(resultCode.toHttpStatus())
                .putHeader("context-type", "application/json;charset=UTF-8");
        CommonResult result = new CommonResult(resultCode);
        ctx.response().end(JsonObject.mapFrom(result).toString());
    }`

In my ProxyInterceptor like this :
`@Slf4j
public class RequestChangeProxyInterceptor implements ProxyInterceptor {

    private JsonArray changeConfig;
    private static final String ORIGIN_NAME = "originName";
    private static final String TARGET_NAME = "targetName";

    private static final String PARAM_NAME = "paramName";
    private static final String FIX_VALUE = "fixValue";

    private static final String CHANGE_TYPE = "changeType";
    public RequestChangeProxyInterceptor(String changeConfig){
        this.changeConfig = new JsonArray(changeConfig);
    }

    @Override
    public Future<ProxyResponse> handleProxyRequest(ProxyContext context) {
        log.info("rename config {}", changeConfig);
        Promise<Void> promise = Promise.promise();
        ProxyRequest request = context.request();
        Buffer buffer = Buffer.buffer();
        ReadStream<Buffer> readStream = request.getBody().stream();
        readStream.handler(bf -> {
           buffer.appendBuffer(bf);
        });
        readStream.endHandler(v -> {
            JsonObject jsonObject = buffer.toJsonObject();
            log.info("body is {}",jsonObject);
            for(Object c : changeConfig.getList()){
                    Map<String,String> config = (Map<String, String>) c;
                    RequestChangeType type = RequestChangeType.valueOf(config.get(CHANGE_TYPE));
                    switch (type){
                        case BodyNameChange:
                            String originName = config.get(ORIGIN_NAME);
                            String targetName = config.get(TARGET_NAME);
                            if(jsonObject.containsKey(originName)){
                                jsonObject.put(targetName,jsonObject.getValue(originName));
                                jsonObject.remove(originName);
                            }
                            break;
                        case BodyValueFix:
                            String paramName = config.get(PARAM_NAME);
                            String fixValue = config.get(FIX_VALUE);
                            jsonObject.put(paramName,fixValue);
                    }
            }
            request.setBody(Body.body(jsonObject.toBuffer()));
//            promise.complete();
            promise.fail(new PlatformException(ResultCode.EXECUTION_ERROR));
        });
        Future<Void> future = promise.future();
        future.onFailure(throwable -> {
            request.response().setStatusCode(500).send();
            throw (PlatformException)throwable;

        });
        readStream.resume();
        return promise.future().compose(v -> context.sendRequest());
    }
}`

I fail in the endHandler(just for test),the error log :
`10:23:15.165 [vert.x-eventloop-thread-1] INFO  c.c.h.n.c.a.a.i.RequestChangeProxyInterceptor - rename config [{"changeType":"BodyNameChange","originName":"test","targetName":"test1"},{"changeType":"BodyValueFix","paramName":"fix","fixValue":"10"}]
10:23:15.168 [vert.x-eventloop-thread-1] INFO  c.c.h.n.c.a.a.i.RequestChangeProxyInterceptor - body is {"test":"namechange","fix":"1000"}
10:23:15.176 [vert.x-eventloop-thread-1] ERROR io.vertx.core.impl.ContextBase - Unhandled exception`

this is like in the async method throw exception , the exception is not capture，if use the vertx.exceptionHandler ,it can capture the exception.

**Comment by afei00615** [comment]
If i use a error json fomat data,the buffer.toJsonObject() is also throw an Unhandled exception

**Comment by afei00615** [comment]
Yesterday i try some solution,I think this is a common problem in vert.x web,when throw exception in the async method,the failureHandler can't catch the exception,i saw this is need catch the exception in the method，and then fail() in the code,the handler the exception ourself，my code like this：
`public Future<ProxyResponse> handleProxyRequest(ProxyContext context) {
        log.info("rename config {}", changeConfig);
        Promise<Void> promise = Promise.promise();
        ProxyRequest request = context.request();
        Buffer buffer = Buffer.buffer();
        ReadStream<Buffer> readStream = request.getBody().stream();
        readStream.handler(bf -> {
            buffer.appendBuffer(bf);
        });

        readStream.endHandler(v -> {
            try {
                JsonObject jsonObject = buffer.toJsonObject();
                log.info("body is {}", jsonObject);
                for (Object c : changeConfig.getList()) {
                    Map<String, String> config = (Map<String, String>) c;
                    RequestChangeType type = RequestChangeType.valueOf(config.get(CHANGE_TYPE));
                    switch (type) {
                        case BodyNameChange:
                            String originName = config.get(ORIGIN_NAME);
                            String targetName = config.get(TARGET_NAME);
                            if (jsonObject.containsKey(originName)) {
                                jsonObject.put(targetName, jsonObject.getValue(originName));
                                jsonObject.remove(originName);
                            }
                            break;
                        case BodyValueFix:
                            String paramName = config.get(PARAM_NAME);
                            String fixValue = config.get(FIX_VALUE);
                            jsonObject.put(paramName, fixValue);
                    }
                }
                request.setBody(Body.body(jsonObject.toBuffer()));
                promise.complete();
            }catch (Throwable throwable){
                log.error(throwable.getMessage(),throwable);
                promise.fail(throwable);
            }
        });

        readStream.resume();
        return promise.future().compose(flg -> context.sendRequest(),throwable -> {
            ProxyResponse proxyResponse = VertxUtils.getProxyResponse(context,ResultCode.EXECUTION_ERROR);
            return Future.succeededFuture(proxyResponse);
        });
    }`

there are other solution for this problem？
