### ISSUE TITLE
HttpServerRequest with null properties in OriginSelector 

### ISSUE THREAD

**Issue by akoufa** [eclipse-vertx/vertx-http-proxy#54]
I am using Vertx Proxy 4.4.5 in Quarkus with Vertx and Reactive routes. What I have observed is that using the originSelector the HttpServerRequest has all it's properties as null.

Example setup:

```
fun init(@Observes router: Router) {

        val proxyClient = vertx.createHttpClient()
        val proxy = HttpProxy.reverseProxy(proxyClient)
        proxy.originSelector { req ->
            Future.succeededFuture(resolveOrigin(req))
        }
        proxy.addInterceptor(object : ProxyInterceptor {
            override fun handleProxyRequest(context: ProxyContext): Future<ProxyResponse> {
                return context.sendRequest()
            }
        })
     
        router.route("/*").handler { rc -> proxy.handle(rc.request()) }
    }
```

**Comment by geoand** [comment]
@akoufa If I were you, I would attach a sample application as it makes it a lot easier for maintainers to go straight to the crux of the problem instead of having to setup a Maven project with the proper dependencies,  language support etc.

**Comment by akoufa** [comment]
@geoand Thanks for the tip.

Here is a repository of a simple reproducer. The error description above has a snippte using Kotlin but I have proceeded creating a simple reproducer using Java and Maven.

https://github.com/akoufa/quarkus-issues

Also the following screenshot of the debugger displays the issue.

<img width="1477" alt="image" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/4354310/110f7244-d56f-4fd8-8ea6-9ff7d74a688c">

**Comment by geoand** [comment]
🙏🏼
