### ISSUE TITLE
Spring Cloud Gateway alternative or bug?

### ISSUE THREAD

**Issue by akoufa** [eclipse-vertx/vertx-http-proxy#55]
Hello I am trying the following:

I am using the vertx-http-proxy in a Quarkus project and I am trying to implement a Gateway similar to the Spring Cloud Gateway. 

What I want to achieve is proxying request like:

https://proxy.com/prx/users --> https://example.com/users

When running the service locally I want to proxy requests like:

http://localhost:8081/prx/users --> https://example.com/users

Unfortunately by reading the docs and trying different variants by using interceptors, originSelector and originRequestProvider I was not able to achieve the functiontality needed either because I was getting similar to this: 

```
java.net.UnknownHostException: https:/example.com nodename nor servname provided, or not known
```

or by getting and issues that an Http requests used Https port etc. 

Is this functionality not supported yet or does this happen to be a bug ?

**Comment by tsegismont** [comment]
Can you share a small reproducer of the program that gives you this error message?

**Comment by tsegismont** [comment]
Closing for lack of reproducing method. For the record, here's an example of prefix removal with an interceptor:

```java
class ProductPathInterceptor implements ProxyInterceptor {
  @Override
  public Future<ProxyResponse> handleProxyRequest(ProxyContext context) {
    ProxyRequest proxyRequest = context.request();
    proxyRequest.setURI("/annoying-prefix" + proxyRequest.getURI());
    return context.sendRequest();
  }
}
```
