### ISSUE TITLE
ipv6 port problem when extracting information from the authority data

### ISSUE THREAD

**Issue by ecejnj42** [eclipse-vertx/vertx-http-proxy#56]
### Questions

An exception is thrown on ipv6 environments because the authority information could be described using an ipv6 ip address.
In such situations, the ipv6 uses ":" as separator for address fields, therefore when also using the ":" to look for the port information is misleading.
A simple example for ipv6 authority info is like this one: "[7a03:908:671:b520:ba27:bbff:ffff:fed2]:1234"

Class "io.vertx.httpproxy.impl.ProxiedRequest" uses some code like this:

` String proxiedAuthority = proxiedRequest.host();

    int idx = proxiedAuthority.indexOf(':');
    String proxiedHost;
    int proxiedPort;
    if (idx == -1) {
      proxiedHost = proxiedAuthority;
      proxiedPort = -1;
    } else {
      proxiedHost = proxiedAuthority.substring(0, idx);
      proxiedPort = Integer.parseInt(proxiedAuthority.substring(idx + 1));
    }`

This causes the following exception when authority is ipv6 format:

`java.lang.NumberFormatException: For input string: "1b74:8f:f43b::1]:80" at java.lang.NumberFormatException. forInputString(NumberFormatException.java:67) 
at java.lang.Integer.parseInt(Integer.java:668)
at java.lang.Integer.parseInt(Integer.java:786)
at io.vertx.httpproxy.impl.ProxiedRequest.sendRequest (ProxiedRequest.java:186)
at io.vertx.httpproxy.impl.ProxiedRequest.send(ProxiedRequest.java:238)`

### Version

io.vertx 4.5.1

### Context

ipv6 environment over an already proxied request.

### Do you have a reproducer?

Reproduce easily on a test just setting the authority to **"[7a03:908:671:b520:ba27:bbff:ffff:fed2]:1234"**

### Steps to reproduce

-

### Extra

Tested on linux 6.2.0-37-generic with jdk 17.

**Comment by tsegismont** [comment]
Thanks for the report, can you contribute the fix?

**Comment by vietj** [comment]
instead this code should use proxiedRequest.authority() that returns a proper host/port object

**Comment by chevaris** [comment]
Code in master does not have the problem

**Comment by ecejnj42** [comment]
Sorry, I cannot fix it due to legal issues.

**Comment by vietj** [comment]
hum ok
