### ISSUE TITLE
[Performance] Improve parsing dates and times

### ISSUE THREAD

**Issue by lucaspouzac** [eclipse-vertx/vertx-http-proxy#57]
Actually, `io.vertx.httpproxy.impl.ParseUtils` use SimpleDateFormat to parse a date. 

It would certainly be possible to improve memory consumption, perhaps using another more efficient method (LocalDateTime.parse ?)

**Java Flight Recorder during 300s**
I observe more than 4% of the memory consumption of my application linked to this analysis.

Screenshot showing 1,3% of memory usage.
![image](https://github.com/eclipse-vertx/vertx-http-proxy/assets/758899/ef0160ec-239a-4862-b572-c05666b0bdce)

Observed with the version 4.5.1 (from quarkus 3.7.0)

**Comment by vietj** [comment]
do you mind contributing a patch @lucaspouzac ?

**Comment by lucaspouzac** [comment]
Ok, next thursday.

**Comment by tsegismont** [comment]
Fixed by 324efed
