### ISSUE TITLE
Is there any way to access session?

### ISSUE THREAD

**Issue by yameizi001** [eclipse-vertx/vertx-http-proxy#74]
#### Describe the feature

I want to use session in ProxyInterceptor, is there any way to access session? If has, how to get it. Thanks very much!

**Comment by tsegismont** [comment]
It's not currently possible. As a workaround you can put a reference to the Vert.x Web `RoutingContext` in local context data with `io.vertx.core.Context#putLocal` before handing over the request to proxy, then retrieve it in the interceptor with `io.vertx.core.Context#getLocal`.

We have plans to let users provide any kind of contextual data in #71

**Comment by vietj** [comment]
I think it is better to use https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/WebServerRequest.java , casting the HttpServerRequest to WebServerRequest and then get the routing context
