### ISSUE TITLE
Confusing message when target proxy is unreachable (vertx-http-proxy embedded in quarkus)

### ISSUE THREAD

**Issue by patrice-conil** [eclipse-vertx/vertx-http-proxy#75]
### Version
Which version(s) did you encounter this bug ?
quarkus 3.11.0 (vertx-http-proxy 4.5.7)

### Context

I encountered an exception  "java.lang.IllegalStateException: Request has already been read" when target proxy is unreachable.

### Do you have a reproducer?
Reproducer is : [here](https://github.com/patrice-conil/quarkus-vertx-proxy.git)
### Steps to reproduce

1. Launch application ./gradlew quarkusDev
2. Call http://localhost:8080/anyUri
3. See "Request has already been read"
4. Start a webserver on port 8888
5. Call http://localhost:8080/anyUri (twice because second call should trigger a 403)
6. Everything goes fine

### Extra
JVM temurin-17
MacOS Sonoma 14.4.1 (23E224)

**Comment by yameizi001** [comment]
@tsegismont I've submitted a pr that might fix this , see #84 . Please see if it works，thanks.

**Comment by tsegismont** [comment]
Verified that the issue has been fixed by #84
