### ISSUE TITLE
Proxied request only ignores host header with "host" in lower camel case

### ISSUE THREAD

**Issue by joelholzerxovis** [eclipse-vertx/vertx-http-proxy#77]
### Version

4.5.8

### Context

I encountered an edge case which is not handled properly. The method `sendRequest` in the class `ProxiedRequest` ignores on line 173 the "host" header. In our application, I encountered the issue, that the "Host" header is starting with an Uppercase letter. Therefore it is added to the request on line 174, but it shouldn't.

In my opinion, line 173 should be changed to  
`if (!HOP_BY_HOP_HEADERS.contains(name) && !name.equalsIgnoreCase("host")) {`

### Hint

I can create a pull request to change this line and extend the test `ProxyRequestTest#testUpdateRequestHeaders`

**Comment by tsegismont** [comment]
Thank you @joelholzerxovis 

Yes, please go ahead, I'll review your PR.

**Comment by joelholzerxovis** [comment]
Thank you @tsegismont! I have created a pull request. Thank you for reviewing it.

**Comment by tsegismont** [comment]
Fixed by #79
