### ISSUE TITLE
Error for modify body before gzip response

### ISSUE THREAD

**Issue by nnzbz** [eclipse-vertx/vertx-http-proxy#89]
### Questions

Error for modify body before gzip response，browser developer tools network show "(failed)net::ERR_CONTENT_DECODING_FAILED"

### Version

4.5.8

### Context

My code referenced https://vertx.io/docs/vertx-http-proxy/java/#_interception_control, but when proxy response gzip occur "ERR_CONTENT_DECODING_FAILED" error in brower.

### Do you have a reproducer?

No

### Steps to reproduce

No

### Extra

No

**Comment by tsegismont** [comment]
Can you please add more info to help us reproduce?

- sample client request
- proxy setup (snippets)
- sample backend response

A complete reproducer is even better

**Comment by nnzbz** [comment]
client request:
<img width="630" alt="Screenshot 2024-07-10 at 16 47 41" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/3138908/439846dc-edcc-4c6b-a51c-3ad3b888df58">

response:
<img width="863" alt="Screenshot 2024-07-10 at 16 43 55" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/3138908/60fd24f0-669d-42eb-832c-8aa459938590">

server http config:
<img width="364" alt="Screenshot 2024-07-10 at 16 51 51" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/3138908/3022cd60-3968-4130-9bb6-7219c79205dd">

proxy config(forward kibana):
<img width="165" alt="Screenshot 2024-07-10 at 16 54 20" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/3138908/23e115af-ba93-4bc2-9599-ca30e31d46fe">

modify code:
<img width="517" alt="Screenshot 2024-07-10 at 16 57 36" src="https://github.com/eclipse-vertx/vertx-http-proxy/assets/3138908/d3797f79-ba04-489f-ab4b-5c6df18e25eb">

**Comment by tsegismont** [comment]
So, if I understand correctly:

- the proxy is between the browser and Kibana
- Kibana uses gzip compression for responses

Correct?

**Comment by nnzbz** [comment]
Yes, that's right

**Comment by tsegismont** [comment]
I was able to reproduce.

The problem is that the Kibana response body is encoded with gzip (as indicated by the `content-encoding` header).
So when you get the buffered content (with `BufferingWriteStream`) you cannot transform to `String`, because you're actually looking at binary content.

Instead, you must create the response like this:

```java
          Buffer content = bufferingWriteStream.content();
          proxyResponse.setBody(Body.body(content));
          return context.sendResponse();
```

If you want to inspect the string content, you can do it like this:

```java
          ByteArrayOutputStream baos = new ByteArrayOutputStream();
          try (GZIPInputStream gis = new GZIPInputStream(new ByteArrayInputStream(content.getBytes()))) {
            byte[] buffer = new byte[1024];
            int len;
            while ((len = gis.read(buffer)) != -1) {
              baos.write(buffer, 0, len);
            }
          } catch (IOException e) {
            throw new RuntimeException(e);
          }
          String html = baos.toString(StandardCharsets.UTF_8);
```
